parser: "@typescript-eslint/parser"
env:
  node: true
  commonjs: true
  jest/globals: true
extends:
  - airbnb-base
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - prettier
  - plugin:prettier/recommended
  - plugin:sonarjs/recommended
parserOptions:
  project: ./tsconfig-eslint.json
settings:
  import/parsers:
    "@typescript-eslint/parser":
      - .ts
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: ./
plugins:
  - jest
  - prettier
  - unicorn
rules:
  unicorn/filename-case:
    - error
    - case: kebabCase
      ignore:
        - \.js$
  import/no-extraneous-dependencies:
    - error
    - devDependencies: true # we're using webpack. Ignore devDependency errors
  no-underscore-dangle: 0
  # Modified AirBnb's no-restricted syntax to remove for...of prevention;
  # Sometimes for...of is the most readable option and can also handle more cases (e.g. early return situations)
  # See here for more on this raging debate: https://github.com/airbnb/javascript/issues/1271
  no-restricted-syntax:
    - error
    - selector: "ForInStatement"
      message: "for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array."
    - selector: "LabeledStatement"
      message: "Labels are a form of GOTO; using them makes code confusing and hard to maintain and understand."
    - selector: "WithStatement"
      message: "`with` is disallowed in strict mode because it makes code impossible to predict and optimize."
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: ^_
  no-plusplus: off
  import/prefer-default-export: off
  import/newline-after-import: error
  import/order:
    - warn
    - newlines-between: always
  no-return-await: off
  no-await-in-loop: off
  no-console:
    - error
    - allow:
        - warn
        - error
  "@typescript-eslint/no-use-before-define": warn
  "@typescript-eslint/return-await":
    - error
    - in-try-catch

overrides:
  - files:
      - "**/*.test.ts"
    rules:
      sonarjs/no-duplicate-string: off
  - files:
      - "**/*.js"
    rules:
      "@typescript-eslint/no-var-requires": off
      sonarjs/no-duplicate-string: off
      sonarjs/no-identical-functions: off
