{
 "title": "COVID metrics by county",
 "time": { "from": "now-3y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "county",
    "label": "County(s)",
    "query": "select distinct (county || ' - ' || state || ':::' || id) county_selector from counties order by county_selector;"
   }
  ]
 },
 "panels": [
  {
   "title": "Weekly new cases per 100,000",
   "type": "timeseries",
   "description": "Number of new cases ",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select cm.county, cm.time, cm.val\nfrom get_county_metrics('${__from:date:iso}', '${__to:date:iso}', 'weeklyNewCasesPer100k', '{${county:doublequote}}') as cm;"
    }
   ]
  },
  {
   "title": "Weekly COVID admissions per 100,000",
   "type": "timeseries",
   "description": "Number of patients admitted to the hospital due to COVID per 100,000 people",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select cm.county, cm.time, cm.val\nfrom get_county_metrics('${__from:date:iso}', '${__to:date:iso}', 'weeklyCovidAdmissionsPer100k', '{${county:doublequote}}') as cm;"
    }
   ]
  },
  {
   "title": "ICU capacity %",
   "type": "timeseries",
   "description": "Percentage of ICU beds currently in-use",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "select cm.county, cm.time, cm.val\nfrom get_county_metrics('${__from:date:iso}', '${__to:date:iso}', 'icuCapacityRatio', '{${county:doublequote}}') as cm;"
    }
   ]
  },
  {
   "title": "Beds with COVID patients %",
   "type": "timeseries",
   "description": "Percentage of hospital beds occupied by COVID patients",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "select cm.county, cm.time, cm.val\nfrom get_county_metrics('${__from:date:iso}', '${__to:date:iso}', 'bedsWithCovidPatientsRatio', '{${county:doublequote}}') as cm;"
    }
   ]
  },
  {
   "title": "First vaccination %",
   "type": "timeseries",
   "description": "% of population with first dosage of vaccination",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "select cm.county, cm.time, cm.val\nfrom get_county_metrics('${__from:date:iso}', '${__to:date:iso}', 'vaccinationsInitiatedRatio', '{${county:doublequote}}') as cm;"
    }
   ]
  },
  {
   "title": "Cumulative COVID deaths as population %",
   "type": "timeseries",
   "description": "Number of cumulative deaths resulting from COVID as a percentage of population",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "with allMetrics as (\n  select county_id, county, time, metric_name, val\n  from get_county_metrics('${__from:date:iso}', '${__to:date:iso}', 'deaths', '{${county:doublequote}}')\n),\npopulation as (\n  select cm.county_id, last(cm.val, cm.time) as val\n  from get_county_metrics('${__from:date:iso}', '${__to:date:iso}', 'population', '{${county:doublequote}}') as cm\n  group by cm.county_id\n)\nselect m.county, m.time, m.metric_name, m.val / p.val as val\nfrom allMetrics m\njoin population p on m.county_id = p.county_id"
    }
   ]
  },
  {
   "title": "Completed vaccination %",
   "type": "timeseries",
   "description": "% of population with completed vaccinations (1st & second dose)",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "select cm.county, cm.time, cm.val\nfrom get_county_metrics('${__from:date:iso}', '${__to:date:iso}', 'vaccinationsCompletedRatio', '{${county:doublequote}}') as cm;"
    }
   ]
  },
  {
   "title": "Cumulative deaths",
   "type": "timeseries",
   "description": "Number of cumulative deaths resulting from COVID",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select cm.county, cm.time, cm.val\nfrom get_county_metrics('${__from:date:iso}', '${__to:date:iso}', 'deaths', '{${county:doublequote}}') as cm;"
    }
   ]
  },
  {
   "title": "Populations",
   "type": "timeseries",
   "description": "The total population of each county",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select cm.county, cm.time, cm.val\nfrom get_county_metrics('${__from:date:iso}', '${__to:date:iso}', 'population', '{${county:doublequote}}') as cm"
    }
   ]
  },
  {
   "title": "New deaths (smoothed)",
   "type": "timeseries",
   "description": "A smoothed curve of number of new deaths resulting from COVID to identify trending",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with allMetrics as (\n  select cm.county, cm.time, cm.val\n  from get_county_metrics('${__from:date:iso}', '${__to:date:iso}', 'newDeaths', '{${county:doublequote}}') as cm\n),\nallMetricsSmoothed as (\n\tselect county, asap_smooth(time, val, 25) smoothedMetrics\n\tfrom allMetrics\n\tgroup by county\n)\nselect county, time, value\nfrom allMetricsSmoothed\ncross join unnest(smoothedMetrics);"
    }
   ]
  },
  {
   "title": "Change in cumulative COVID deaths as population %",
   "type": "timeseries",
   "description": "Change in COVID deaths as a % of population. Useful for understanding if a change in something (e.g. vaccinations) impacts death rate",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "with allMetrics as (\n  select county_id, county, time, metric_name, val\n  from get_county_metrics('${__from:date:iso}', '${__to:date:iso}', 'deaths', '{${county:doublequote}}')\n),\npopulation as (\n  select cm.county_id, last(cm.val, cm.time) as val\n  from get_county_metrics('${__from:date:iso}', '${__to:date:iso}', 'population', '{${county:doublequote}}') as cm\n  group by cm.county_id\n),\ndeathsAsPercentOfPopulation as (\n  select m.county, m.time, m.metric_name, m.val / p.val as val\n  from allMetrics m\n  join population p on m.county_id = p.county_id\n),\ndeathRateChange as (\n  select m.county, m.time, m.metric_name, m.val - lag(m.val) over w val\n  from deathsAsPercentOfPopulation m\n  window w as (partition by county order by time)\n),\ndeathRateChangeSmoothed as (\n\tselect county, asap_smooth(time, val, 25) smoothedMetrics\n\tfrom deathRateChange\n\tgroup by county\n)\nselect county, time, value\nfrom deathRateChangeSmoothed\ncross join unnest(smoothedMetrics);"
    }
   ]
  }
 ]
}